### ISSUE TITLE
Reopening Project in Sublime Text

### ISSUE THREAD

**Issue by Shadeslayer345** [spywhere/Javatar#42]
When I close Sublime Text after using Javatar, upon reopening Sublime Text the Javatar Project Folder is automatically opened in the sidebar. Is there a setting to turn this behavior off?

**Comment by spywhere** [comment]
Yes, you could set the `allow_project_restoration` to `false`. This way, your project data will not store and restore upon save/load the files.

Please mind that Sublime Text's default behaviour is not store project data on load except you explicitly save it as project yourself.
