### ISSUE TITLE
Source Folder Being Removed When Closing Project

### ISSUE THREAD

**Issue by daneb** [spywhere/Javatar#49]
Hi @spywhere

In reference to closed issue #48 

Sadly these two options do not work.
I tried them separately and together.
I even dropped it down to 1 second (which it was saving correctly), but upon closing the project (using tail -f) I can see it clear out my "source folder" path.

Thus every time I open the project I have to re-set the "source folder".

There is also some other strangeness where it removed one of my folders as well as inserting an incorrect source folder path from another project (I have no idea how what is happening and trying to replicate).

History as you requested:
https://gist.github.com/daneb/cd28aeea24eaea166372

Thanks
Dane

**Comment by spywhere** [comment]
I will try to reproduce the issue and see if it happen to me or not. I might request more informations or may be some Sublime Text modification if I cannot reproduced.

**Comment by daneb** [comment]
Just let me know and will gladly assist

**Comment by spywhere** [comment]
I just follow the reproduce instruction on the issue #48 and get the idea of what you described before (at first I thought it would be something about file restoration).

The problem might be that you are not save your project to file (`Project > Save Project As...`) but rely on Javatar restoration feature instead. The settings are lost when you close your project (or window rather), but if you let it open and close Sublime Text instead the settings will be restore upon startup of Javatar as restoration feature should work that way.

To solve this problem, when you created your project (with or without settings), save your project to file using `Project > Save Project As...`. This way, Sublime Text will not remove any of project data from your window and makes Javatar happy to use your previous settings again. 

PS. Feels free to comment if you are confused on what I wrote above.

**Comment by daneb** [comment]
Thanks again for clarifying. Spot on that works perfectly!
