### ISSUE TITLE
Java development: Can't add m2 local repository to classpath

### ISSUE THREAD

**Issue by 7specialgems** [spywhere/Javatar#50]
As a: java developer who is working on a maven project
I want: to add my local m2 local repository to the classpath
so that: My linter plugin does not complain about imported classes

Observation:

Using Javatar settings > Dependencies > Add Class Folder, I can only select from a pre-populated list of folders made up of the folder(s) in the workspace, their parents and their children. As such it does not appear possible to add my local maven folder (located in my home folder) to the classpath which Javatar uses

**Comment by spywhere** [comment]
What you observed is correct. Javatar does not show the hidden files and directories by default. You could, however, use a workaround to add your path to the Javatar settings. By adding any folder to your dependency list and change the actual path in the settings file itself.

I will add another option for this settings in v1.0.0 (and also v2.0.0), hopefully you will get the update version within 8 hours.
