### ISSUE TITLE
Huge memory leaks with ST3

### ISSUE THREAD

**Issue by kmwho** [spywhere/Javatar#51]
Hey, I am using St build 3083 on debian 8 (jessie). and i noticed that sublime text is using huge amounts of memory after a while

I tested after disabling all packages and sublime is only using 25-30 mb even after keeping it open for about 18 hours.

These are the results after enabling only javatar plugin. I just have 4 java files open in sublime and I am not even using sublime right now and the memory usage keeps escalating and is very noticable after half an hour

Usages after about an hour and 12 hours of just keeping open (no editing)
![javatar_memory1](https://cloud.githubusercontent.com/assets/3801296/9541729/ede657d0-4d38-11e5-9dd3-098ed571ac5d.jpg)
![javatar_memory2](https://cloud.githubusercontent.com/assets/3801296/9541730/ede694c0-4d38-11e5-9836-67e8d0700b2d.jpg)

**Comment by spywhere** [comment]
Okay, I'll try it on my computer and see which part of it take up a memory.

**Comment by spywhere** [comment]
Here's what I've tested so far...

On the left, an Ubuntu 15.04 with Sublime Text 3083, Package Control and Javatar v1.0.2 with no file opened at all.

In the middle, an Ubuntu 15.04 with Sublime Text 3083, Package Control and Javatar v1.0.2 with one Java file opened.

On the right, an Ubuntu 15.04 with Sublime Text 3083, Package Control and Javatar v1.0.2 with folder opened and configured the Javatar settings.

At the beginning of the test
![_filepane-screen shot 2558-08-29 at 01 59 28](https://cloud.githubusercontent.com/assets/1087399/9560366/884ed8aa-4e39-11e5-9037-8acbba0b2cb7.png)

After 8 and a half hours pass
![_filepane-_filepane-_filepane-screen shot 2558-08-29 at 10 24 52](https://cloud.githubusercontent.com/assets/1087399/9560383/fa487eec-4e3a-11e5-9fa9-3f8878e6fa59.png)

I don't think the OS would matter if my plugin is memory leak however if you could, could you give me your files tree (so I can see how your project structured and replicate it again) and also please send me an action history by pressing Ctrl+Shift+K, Ctrl+Shift+H (not a custom one)

**Comment by kmwho** [comment]
Hey, it's good to see a quick response.I'm out of the city for two days, so I will give you more details as soon as I get back to work on monday.

**Comment by kmwho** [comment]
Here is my directory structure
![javatar3](https://cloud.githubusercontent.com/assets/3801296/9573408/20e2e196-4f8a-11e5-81f0-eaf0c4082651.jpg)

I have very huge images in the res/limg folder (lots of images of 100MP+ size)

source folder is src/  and output folder is bin/

Ctrl+Shift+K,  Ctrl+Shift+H  gives

	## Javatar Report
	### System Informations
	* Javatar Version: `1.0.2`
	* Sublime Version: `3083`
	* Package Path: `/home/kmwho/.config/sublime-text-3/Packages`
	* Javatar Channel: `stable`
	* Sublime Channel: `stable`
	* Is Debug Mode: `False`
	* Platform: `linux`
	* As Packages: `True`
	* Package Control: `True`
	* Architecture: `x64`
	* Javatar's Parent Folder: `Javatar`
	* Is Project: `True`
	* Is File: `True`
	* Is Java: `True`

	### Action List
	1. Startup
	2. Reset all settings
	3. Reset all snippets
	4. Reset all default packages
	5. Read settings
	6. Load snippets
	7. Check news
	8. Ready
	9. Javatar snippet Class.javatar loaded
	10. Analyse snippet [file=Packages/Javatar/snippets/Class.javatar]
	11. Javatar snippet Enumerator.javatar loaded
	12. Analyse snippet [file=Packages/Javatar/snippets/Enumerator.javatar]
	13. Javatar snippet Interface.javatar loaded
	14. Analyse snippet [file=Packages/Javatar/snippets/Interface.javatar]
	15. Load Java default packages
	16. Javatar default package Proto.javatar-packages loaded
	17. Analyse package [file=Packages/Javatar/Developers/Proto.javatar-packages]
	18. Javatar default package JavaSE8.javatar-packages loaded
	19. Analyse package [file=Packages/User/JavaSE8.javatar-packages]
	20. Check packages update
	21. Select item ['Actions History', 'Generate a report on Javatar actions history'] [from_sublime=True]

**Comment by spywhere** [comment]
Alright, I'll try and see if it can be replicated.

**Comment by spywhere** [comment]
I will resolve this issue and release it on a new version (and leave the first version as-is) as I'm planned to release the pre-beta version soon (which might work quite well for most projects).

**Comment by spywhere** [comment]
In Javatar v2.0.0-prebeta, will try to trigger garbage collection when activated a view. This should solve the memory issue by a lot.
