### ISSUE TITLE
Javatar can't find JDK (window) but I have insatll jdk

### ISSUE THREAD

**Issue by Badredapple** [spywhere/Javatar#56]
Each time I open ,it always say " Javatar can not find JDK"..
I install my jdk in C:\Program Files (x86)\Java\jdk1.8.0_60
classpath : .;C:\Program Files (x86)\Java\jdk1.8.0_60\lib\dt.jar;C:\Program Files (x86)\Java\jdk1.8.0_60\lib\tools.jar
path :  C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\;C:\Program Files (x86)\Java\jdk1.8.0_60\bin;C:\Program Files (x86)\Java\jdk1.8.0_60\jre\bin
JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0_60

when I use cmd .I can find my java .but can not use "jdk -version" .cmd only put out "'jdk' 不是内部或外部命令，也不是可运行的程序或批处理文件。"

I just begin use java in sublimetext. how should I do next ?

**Comment by spywhere** [comment]
Could you try checking with this issue #55 ? There is an issue about this still open.

I will close this issue and will use the mentioned issue instead.
