### ISSUE TITLE
Cant Build after a reboot of my computer

### ISSUE THREAD

**Issue by eduardosanzb** [spywhere/Javatar#58]
Hello Dude, First thank you for Javatar, I´m having a little bit of troubles trying to build, everything was working flawless but after a reboot of my computer javatar cant build, I think it can build but is not making an out for the bin folder.
I already check and yes it it building because I inject a compile error and actually javatar found it, well came up the error. So I believe what is happening is that is not making the file in the bin folder.
![Screenshot](https://github.com/eduardosanzb/trainingLanguages/blob/master/bugs/img/Screen%20Shot%202016-01-05%20at%207.17.56%20PM.png?raw=true)

### System Informations
* Javatar Version: `1.0.2`
* Sublime Version: `3083`
* Package Path: `/Users/eduardosanzb/Library/Application Support/Sublime Text 3/Packages`
* Javatar Channel: `stable`
* Sublime Channel: `stable`
* Is Debug Mode: `False`
* Platform: `osx`
* As Packages: `True`
* Package Control: `True`
* Architecture: `x64`
* Javatar's Parent Folder: `Javatar`
* Is Project: `True`
* Is File: `True`
* Is Java: `True`

### Action List
1. Startup
2. Reset all settings
3. Reset all snippets
4. Reset all default packages
5. Read settings
6. Load snippets
7. Check news
8. Ready
9. Javatar snippet Class.javatar loaded
10. Analyse snippet [file=Packages/Javatar/snippets/Class.javatar]
11. Javatar snippet Enumerator.javatar loaded
12. Analyse snippet [file=Packages/Javatar/snippets/Enumerator.javatar]
13. Javatar snippet Interface.javatar loaded
14. Analyse snippet [file=Packages/Javatar/snippets/Interface.javatar]
15. Load Java default packages
16. Javatar default package Proto.javatar-packages loaded
17. Analyse package [file=Packages/Javatar/Developers/Proto.javatar-packages]
18. Javatar default package JavaSE8.javatar-packages loaded
19. Analyse package [file=Packages/User/JavaSE8.javatar-packages]
20. Check packages update
21. Select item ['Builds...', 'Build system'] [from_sublime=True]
22. Select item ['Current Class', 'Build current class'] [from_sublime=False]
23. Build [build_type=class]
24. Build file
25. Building Finished with Warning [0.03s]
26. Select item ['Builds...', 'Build system'] [from_sublime=False]
27. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=False]
28. Select item ['Builds...', 'Build system'] [from_sublime=False]
29. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
30. Build [build_type=project]
31. Build all
32. Building Finished with Warning [0.15s]
33. Select item ['Javatar Settings...', 'Adjust Javatar settings'] [from_sublime=False]
34. Select item ['Dependencies...', 'Manage default dependencies'] [from_sublime=False]
35. Select item ['Back', 'Back to previous menu'] [from_sublime=False]
36. Select item ['Set Default JDK', 'Set default JDK for builds and runs'] [from_sublime=False]
37. Project Settings [type=set_jdk]
38. Select item ['Javatar Settings...', 'Adjust Javatar settings'] [from_sublime=False]
39. Select item ['Set Default JDK', 'Set default JDK for builds and runs'] [from_sublime=False]
40. Project Settings [type=set_jdk]
41. Select item ['Packages Manager...', 'Javatar packages manager'] [from_sublime=False]
42. Select item ['Reload and Update packages', 'Reload all packages and update packages list'] [from_sublime=False]
43. Reload Packages
44. Reset all default packages
45. Load Java default packages
46. Javatar default package Proto.javatar-packages loaded
47. Analyse package [file=Packages/Javatar/Developers/Proto.javatar-packages]
48. Javatar default package JavaSE8.javatar-packages loaded
49. Analyse package [file=Packages/User/JavaSE8.javatar-packages]
50. Check packages update
51. Select item ['Operations...', 'Do a Java operation'] [from_sublime=False]
52. Select item ['Back', 'Back to previous menu'] [from_sublime=False]
53. Select item ['Builds...', 'Build system'] [from_sublime=False]
54. Select item ['Current Class', 'Build current class'] [from_sublime=False]
55. Build [build_type=class]
56. Build file
57. Building Finished [0.00s]
58. Exit menu [from_sublime=False]
59. Select item ['Builds...', 'Build system'] [from_sublime=True]
60. Select item ['Current Class', 'Build current class'] [from_sublime=False]
61. Build [build_type=class]
62. Build file
63. Building Finished [0.00s]
64. Select item ['Builds...', 'Build system'] [from_sublime=False]
65. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=False]
66. Create package [package=]
67. Create package [package=j]
68. Create package [package=ja]
69. Create package [package=jav]
70. Create package [package=java]
71. Create package [package=javat]
72. Create package [package=javata]
73. Create package [package=javatar]
74. Create package [package=javata]
75. Create package [package=javat]
76. Create package [package=java]
77. Create package [package=jav]
78. Create package [package=ja]
79. Create package [package=j]
80. Create package [package=]
81. Create package [package=]
82. Create package [package=]
83. Create package [package=]
84. Create package [package=]
85. Create package [package=]
86. Create package [package=]
87. Create package [package=]
88. Create package [package=]
89. Create package [package=]
90. Create package [package=]
91. Create package [package=]
92. Create package [package=]
93. Select item ['Builds...', 'Build system'] [from_sublime=False]
94. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
95. Build [build_type=project]
96. Build all
97. Building Finished with Warning [0.11s]
98. Select item ['Builds...', 'Build system'] [from_sublime=False]
99. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
100. Build [build_type=project]
101. Build all
102. Building Finished with Warning [0.12s]
103. Select item ['Packages Manager...', 'Javatar packages manager'] [from_sublime=False]
104. Select item ['Package Tools...', 'Tools for package creator'] [from_sublime=False]
105. Select item ['Back', 'Back to previous menu'] [from_sublime=False]
106. Select item ['Back', 'Back to previous menu'] [from_sublime=False]
107. Select item ['Javatar Settings...', 'Adjust Javatar settings'] [from_sublime=False]
108. Select item ['Set Default JDK', 'Set default JDK for builds and runs'] [from_sublime=False]
109. Project Settings [type=set_jdk]
110. Select item ['Builds...', 'Build system'] [from_sublime=False]
111. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
112. Build [build_type=project]
113. Build all
114. Building Finished with Warning [0.12s]
115. Select item ['Help and Support...', 'Utilities for Help and Support on Javatar'] [from_sublime=False]
116. Select item ['Actions History', 'Generate a report on Javatar actions history'] [from_sublime=False]

## P.D.
Also I believe is not reading the bin folder files.

**Comment by spywhere** [comment]
Thanks to your screenshot. The problem is you did not set your source folder (you can see that the `Package: ` show the prefix `src.` which means your `src` folder is being use as default package).

What you have to do is set the source folder to your `src` folder again, this should solve the problem. This can be happen if you have configured the Javatar and did not save as a project since the settings will be lost after restart Sublime Text.

The problem can be permanently solved by saving your project as `.sublime-project` by using the Sublime Texts's menu under `Project`. This will store all the project-related settings to your project file and hence the settings will not be lost again.

Let me know if it's work :)

**Comment by eduardosanzb** [comment]
Thank you so much. U rock!
