### ISSUE TITLE
build with warning

### ISSUE THREAD

**Issue by JeffreyzZhang** [spywhere/Javatar#60]
Hi, I just installed Javatar by Package Control. But its always building with error.

<img width="732" alt="2016-02-11 07 30 07 pm" src="https://cloud.githubusercontent.com/assets/4316567/12995537/2436593e-d0f6-11e5-8d44-f29459304e3a.png">

**Comment by spywhere** [comment]
That would be your code that has the warning. However, Javatar should show you the warning message from the compiler (which in this case, if you didn't close it, it's not showing). To solve this try increase the `build_log_delay` in the user's settings and try compile the code again. This should show the compilation message.
