### ISSUE TITLE
Create Class menu option is missing

### ISSUE THREAD

**Issue by jotadepicas** [spywhere/Javatar#62]
Hi, I'm giving a try to javatar but when I go to the "Create" menu, only two options are given: "Back" and "Package".
![javatar](https://cloud.githubusercontent.com/assets/1919819/15454508/c5ff1a9e-2010-11e6-9e1f-c62423e934c6.png)

I don't see any particular errors in the console. I'm using ST3 build 3103. Thanks!

**Comment by spywhere** [comment]
Did you see the status bar text showing that Javatar is starting up?
![javatar](https://cloud.githubusercontent.com/assets/1087399/15458788/858a9390-20c8-11e6-9215-8144ba619dd9.png)
If so, please wait for a few seconds until Javatar is ready.

After that can you give me an Action History report (via `Ctrl/Cmd+Shift+K, Ctrl/Cmd+Shift+H`)?

For your information, when Javatar starts it should show a message in the console state that files have been loaded.
![javatar](https://cloud.githubusercontent.com/assets/1087399/15458878/622c3e66-20c9-11e6-8a41-394ff0990a3b.png)

**Comment by jotadepicas** [comment]
Hi, sorry for the delay. This is really strange, it now works.... and I didn't do anything but restarting my computer. I had restarted sublime before but that didn't fixed it. I'm glad that I took a screenshot of the problem so you know it actually happened :P

For the record the console show this:

Javatar snippet Class.javatar loaded
Javatar snippet Enumerator.javatar loaded
Javatar snippet Interface.javatar loaded
reloading Packages/User/Javatar.sublime-settings
Javatar package "Java Standard Edition 8" loaded with 4385 classes in 213 packages
[Javatar] Use default Java version [JDK1.8.0u74]
reloading Packages/User/Javatar.sublime-settings

If the problem appears again, I will gather the Action History report and send it.

thanks!

**Comment by UtkarshVerma** [comment]
I'm also facing this issue. Any solution to it?
My report:
```
## Javatar Report
### System Informations
* Javatar Version: `1.0.2`
* Sublime Version: `3176`
* Package Path: `C:\Users\Utkarsh\AppData\Roaming\Sublime Text 3\Packages`
* Javatar Channel: `stable`
* Sublime Channel: `stable`
* Is Debug Mode: `False`
* Platform: `windows`
* As Packages: `True`
* Package Control: `True`
* Architecture: `x64`
* Javatar's Parent Folder: `Javatar`
* Is Project: `True`
* Is File: `False`
* Is Java: `False`

### Action List
1. Startup
2. Reset all settings
3. Reset all snippets
4. Reset all default packages
5. Read settings
6. Load snippets
7. Check news
8. Ready
9. Javatar snippet Class.javatar loaded
10. Analyse snippet [file=Packages/Javatar/snippets/Class.javatar]
11. Javatar snippet Enumerator.javatar loaded
12. Analyse snippet [file=Packages/Javatar/snippets/Enumerator.javatar]
13. Javatar snippet Interface.javatar loaded
14. Analyse snippet [file=Packages/Javatar/snippets/Interface.javatar]
15. Load Java default packages
16. Javatar default package Proto.javatar-packages loaded
17. Analyse package [file=Packages/Javatar/Developers/Proto.javatar-packages]
18. Javatar default package JavaSE8.javatar-packages loaded
19. Analyse package [file=Packages/User/JavaSE8.javatar-packages]
20. Check packages update
21. Select item ['Create...', 'Create a new class or package'] [from_sublime=True]
22. Exit menu [from_sublime=False]
23. Select item ['Actions History', 'Generate a report on Javatar actions history'] [from_sublime=True]
24. Select item ['Actions History', 'Generate a report on Javatar actions history'] [from_sublime=False]
```
