### ISSUE TITLE
Javatar cancel the builds

### ISSUE THREAD

**Issue by MayankLalaiya** [spywhere/Javatar#64]
**When i try to build current class or working class stats bar shows building cancelled.**

**Comment by spywhere** [comment]
Did you close the build log while Javatar is building your project?

**Comment by MayankLalaiya** [comment]
No

**Comment by spywhere** [comment]
Do Javatar display any build log at all? If not, try increase `build_log_delay ` in the user's settings and test it again.

**Comment by MayankLalaiya** [comment]
Now i solved it.

Thank You.
