### ISSUE TITLE
Javatar Unable to detect OpenJDK on Ubuntu 16.04

### ISSUE THREAD

**Issue by ROODAY** [spywhere/Javatar#70]
I'm running OpenJDK 9, yet every time I start Sublime Text (3) I get the error:  "Javatar cannot find JDK installed on your computer." I tried overriding the jdk installation in user settings, but I still get the same error. Is there something I'm missing?

**Comment by spywhere** [comment]
Please checkout the issue #65 for potential fix. If the issue still persist feel free to open the issue again along with some of your settings and installation of both Java and Javatar.

**Comment by ROODAY** [comment]
I wasn't able to find a fix through those issues, but what did work for me was running this command in terminal: `sudo apt-get install openjdk-8*`. I'm guessing I may have installed an incomplete version of openjdk9 somehow, so I openjdk9 seemed to be the fix.
